# Lab: Dashboarding with a pivot table

This Lab will give you some practice building dashboards to create interactive plots.

We will expand upon some methods using pivot tables to plot connected plots for dashboards.

This is a model for how to build a dashboard with *categorical* rows and columns.

**NOTE: It is *highly* recommended that you hit "Save & Grade" after you answer each prompt in order to catch any errors in order.**

## Step 1: Look at toy dataset

We are going to use the data frame, `df`, below to make a [pivot table](https://pandas.pydata.org/docs/reference/api/pandas.pivot_table.html).

First, take a look at this `df` dataframe to get familiar with it:

In [1]:
#grade (keep this code in this cell and DO NOT DELETE THIS LINE) -- this code should show up in your Lab!
import pandas as pd

df = pd.DataFrame({
    'A':['bar', 'bar', 'bar', 'bar', 'bar', 'bar', 'bar', 'bar', 'foo', 'foo', 'foo', 'foo', 'foo', 'foo', 'foo', 'foo', 'foo', 'foobar', 'foobar', 'foobar', 'foobar', 'foobar', 'foobar', 'foobar', 'foobar', 'foobar', 'foobar', 'foobar'],
    'B':['three', 'three', 'three', 'three', 'three', 'three', 'three', 'two', 'one', 'one', 'two', 'one', 'three', 'one', 'three', 'two', 'three', 'two', 'one', 'three', 'three', 'three', 'three', 'two', 'two', 'three', 'one', 'three'],
    'C':['medium', 'small', 'medium', 'large', 'medium', 'medium', 'medium', 'large', 'large', 'small', 'medium', 'small', 'small', 'large', 'large', 'small', 'small', 'large', 'small', 'medium', 'medium', 'small', 'medium', 'medium', 'small', 'medium', 'small', 'medium'],
    'D':[102.0, 1.0, 15.0, 12.0, 6.0, 7.0, 7.0, 6.0, 7.0, 6.0, 6.0, 102.0, 7.0, 88.0, 102.0, 15.0, 7.0, 2.0, 88.0, 7.0, 1.0, 7.0, 102.0, 7.0, 2.0, 15.0, 2.0, 7.0],
    'E':[9.0, 9.0, 9.0, 8.0, 8.0, 8.0, 2.0, 2.0, 8.0, 8.0, 8.0, 9.0, 8.0, 8.0, 9.0, 9.0, 22.0, 8.0, 9.0, 8.0, 2.0, 2.0, 11.9, 5.0, 9.0, 8.0, 9.0, 11.9]
})


df

         A      B       C      D     E
0      bar  three  medium  102.0   9.0
1      bar  three   small    1.0   9.0
2      bar  three  medium   15.0   9.0
3      bar  three   large   12.0   8.0
4      bar  three  medium    6.0   8.0
5      bar  three  medium    7.0   8.0
6      bar  three  medium    7.0   2.0
7      bar    two   large    6.0   2.0
8      foo    one   large    7.0   8.0
9      foo    one   small    6.0   8.0
10     foo    two  medium    6.0   8.0
11     foo    one   small  102.0   9.0
12     foo  three   small    7.0   8.0
13     foo    one   large   88.0   8.0
14     foo  three   large  102.0   9.0
15     foo    two   small   15.0   9.0
16     foo  three   small    7.0  22.0
17  foobar    two   large    2.0   8.0
18  foobar    one   small   88.0   9.0
19  foobar  three  medium    7.0   8.0
20  foobar  three  medium    1.0   2.0
21  foobar  three   small    7.0   2.0
22  foobar  three  medium  102.0  11.9
23  foobar    two  medium    7.0   5.0
24  foobar    two   small    2.0   9.0
25  foobar  three  medium   15.0   8.0
26  foobar    one   small    2.0   9.0
27  foobar  three  medium    7.0  11.9

## Step 2: Create pivot table

Create a pivot table such that the dataframe will have the mean of all of the values of column "E" into bins of columns "C" and "A" where "C" values will be the row name and "A" values will be the column name.

Set the parameter `fill_value = np.nan` to fill in NaN's for missing values in the table.

In [2]:
#grade (write your code in this cell and DO NOT DELETE THIS LINE)
import numpy as np

table = pd.pivot_table(df, values='E', index='C', columns='A', aggfunc='mean', fill_value=np.nan)
table

A       bar        foo  foobar
C
large   5.0   8.333333    8.00
medium  7.2   8.000000    7.80
small   9.0  11.200000    7.25

## Step 3: Create Heatmap

Create a gridheatmap figure with the "Blues" colorscheme using `bqplot`.

Label the x-axis with 'A' and the yaxis with 'C' and place the color axis on the right side of the plot.

The `color` of this grid heatmap should be the *values* of the table (`table.values`) and the rows should be the names of the rows of your table, stored in a variable **called `row_names`**, and the columns should be the columns of your table stored in a variable **called `column_names`**.
 * Hint \#1: Check the pivot table Lab section for a reminder of how to get these from your table
 * Hint \#2: Not sure how to set row and column values?  Try looking at the doc strings with `bqplot.GridHeatMap?`

Add in an interaction in which you `select` when you `click`.  When a cell is selected, fill the cell with the color magenta.

Place this heatmap mark in a figure.

**Call the heatmap variable `heatmap` and the figure object `fig`.**

In [3]:
#grade (write your code in this cell and DO NOT DELETE THIS LINE)
import bqplot.pyplot as plt
from bqplot import ColorScale, OrdinalScale, GridHeatMap, Figure, Axis, ColorAxis

# Define row and column labels
row_names = table.index.tolist()
column_names = table.columns.tolist()

# Define scales
color_scale = ColorScale(scheme="Blues")
x_scale = OrdinalScale()
y_scale = OrdinalScale()

# Create heatmap
heatmap = GridHeatMap(
    color=table.values,
    row=row_names,
    column=column_names,
    scales={'color': color_scale, 'row': y_scale, 'column': x_scale},
    interactions={'click': 'select'},
    selected_style={'fill': 'magenta'}
)

# Define axes
x_axis = Axis(label='A', scale=x_scale, side='bottom')
y_axis = Axis(label='C', scale=y_scale, orientation='vertical')
color_axis = ColorAxis(scale=color_scale, side='right')

# Create figure with correct axes
fig = Figure(marks=[heatmap], axes=[x_axis, y_axis, color_axis], title="Heatmap of Mean E")

fig

Figure(axes=[Axis(label='A', scale=OrdinalScale(), side='bottom'), Axis(label='C', orientation='vertical', sca…

## Step 4: Create a histogram of column "E" with a "hard-coded" cell selection

### Step 4.1: Get row/column names with hardcoded values

Set an integer **called `i`** to the cell value 0 and another integer **called `j`** and set it to 0.

Get the column entry associated with this `i` value and set it to a **variable called `column_select_name`** and get the row entry associated with this `j` value and set it to a **variable called `row_select_name`**.

In [4]:
#grade (write your code in this cell and DO NOT DELETE THIS LINE)
i, j = 0, 0  # Hardcoded values
column_select_name = column_names[i]
row_select_name = row_names[j]

### Step 4.2: Hardcoded subset dataframe

Create a subset dataframe **called `df_subset`** which is a subset of `df` that contains only the data where the "A" column is equal to `column_select_name` and "C" column is equal to `row_select_name`.

Hint: not sure how to subset?
  * check out the [`.isin` function](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isin.html)
  * there are two conditions that need to be met -- you can do this by making `df_subset` in two steps or using a [boolean `&` symbol](https://stackoverflow.com/questions/21415661/logical-operators-for-boolean-indexing-in-pandas)

In [5]:
#grade (write your code in this cell and DO NOT DELETE THIS LINE)
df_subset = df[(df["A"] == column_select_name) & (df["C"] == row_select_name)]
df_subset

     A      B      C     D    E
3  bar  three  large  12.0  8.0
7  bar    two  large   6.0  2.0

### Step 4.3: Put it all together in a function

Create a function **called `subsetting_function`** that takes as inputs **in this order** (1) a dataframe, (2) the column names of your grid heatmap, (3) the row names of your grid heatmap, (4) a cell number for the columns (like `i`) and (5) a cell number for the rows (like `j`) and outputs the subset dataframe that results from this selection.

In [6]:
#grade (write your code in this cell and DO NOT DELETE THIS LINE)
def subsetting_function(df, column_names, row_names, i, j):
    col_select = column_names[i]
    row_select = row_names[j]
    return df[(df["A"] == col_select) & (df["C"] == row_select)]

### Step 4.4: Use function to get a data subset for plotting

Using your `subsetting_function`, create a subset dataframe **called `df_subset_plot`** for row, column = 1,0.

In [7]:
#grade (write your code in this cell and DO NOT DELETE THIS LINE)
df_subset_plot = subsetting_function(df, column_names, row_names, 0, 1)  # i = 0, j = 1
df_subset_plot

     A      B       C      D    E
0  bar  three  medium  102.0  9.0
2  bar  three  medium   15.0  9.0
4  bar  three  medium    6.0  8.0
5  bar  three  medium    7.0  8.0
6  bar  three  medium    7.0  2.0

### Step 4.5: Histogram with this subset dataframe

Using the bqplot `Bars` mark, create a plot of the *mean* of column "D" for each unique value of column "B" in `df_subset_plot`.  **Call this bar mark `bars`.**  Put this bar mark into a figure **called `fig_bars`** and label the x-axis as "B" and the y-axis as "Mean D".

Hints:
 * not sure of the parameters of `Bars`?  try `bqplot.Bars?`
 * not sure about how to "deposit" 'D' onto 'B'?  What function can you us in Pandas for this? (Check out what we did for the Pandas lab).  What are the `.index` and `.values` of this series?
 * not sure what to use for scales? What type of variable is `df`'s "B" column (x-scale)? What type is the "D" column (y-scale)?

In [8]:
#grade (write your code in this cell and DO NOT DELETE THIS LINE)
from bqplot import Bars, OrdinalScale, LinearScale

# Define scales
x_scale_bars = OrdinalScale()
y_scale_bars = LinearScale()

# Compute mean D for each unique value of B in df_subset_plot
if not df_subset_plot.empty:
    mean_D_by_B = df_subset_plot.groupby("B")["D"].mean()
    x_values = mean_D_by_B.index.tolist()
    y_values = mean_D_by_B.values.tolist()
else:
    x_values = ['']  # Empty category if no data
    y_values = [0]   # Default y-value when no data

# Create bars mark
bars = Bars(
    x=x_values,
    y=y_values,
    scales={'x': x_scale_bars, 'y': y_scale_bars}
)

# Define correct axes
x_axis_bars = Axis(label='B', scale=x_scale_bars, side='bottom')
y_axis_bars = Axis(label='Mean D', scale=y_scale_bars, orientation='vertical', side='left')

# Create figure with correct axes
fig_bars = Figure(marks=[bars], axes=[x_axis_bars, y_axis_bars], title="Mean D by B")

fig_bars

Figure(axes=[Axis(label='B', scale=OrdinalScale(), side='bottom'), Axis(label='Mean D', orientation='vertical'…

## Step 5: Create selection function

Create a function **called `on_selection`** which is tied to the heatmap with an `.observe` call on the `heatmap`'s `selected` key.

The function should only allow for *one* selection at a time (i.e., no multiple cell selection).

The function should change the data used in the `bars` plot based on the cell selected by the user.

**NOTE:** Be sure to account for the fact that some cell's will result in empty subset dataframes -- this will lead to an error.  To fix this, make sure the `bars` plot has the value of an empty string (`['']`) on its x-axis ("B") and the value of `[0]` on the y-axis ("Mean B") when the subset dataframe is an empty string.

In [9]:
#grade (write your code in this cell and DO NOT DELETE THIS LINE)
def on_selection(change):
    
    selected_cell = change['owner'].selected  # Get selected cell coordinates
    print("Selected Cell:", selected_cell)  # Debugging statement

    # Ensure only a single cell is selected
    if isinstance(selected_cell, list) and len(selected_cell) > 0:
        # Take only the first selection (ignoring others)
        i, j = selected_cell[0]  

        # Ensure indices are within bounds
        if i < len(row_names) and j < len(column_names):
            column_select_name = column_names[j]  # "A" column value
            row_select_name = row_names[i]  # "C" column value

            print(f"Selected A: {column_select_name}, Selected C: {row_select_name}")  # Debugging

            # Generate the subset dataframe
            df_subset_plot = df[(df['A'] == column_select_name) & (df['C'] == row_select_name)]

            # Handle empty dataframe case
            if df_subset_plot.empty:
                bars.x = ['']  # Empty category
                bars.y = [0]   # Default zero value
                print("No matching data found.")  # Debugging
            else:
                # Aggregate mean "D" for each unique value in "B"
                mean_d_per_b = df_subset_plot.groupby("B")["D"].mean()

                # Update bars plot data
                bars.x = mean_d_per_b.index.values
                bars.y = mean_d_per_b.values

                print("Updated bars:", bars.x, bars.y)  # Debugging

           
            change['owner'].selected = [selected_cell[0]]  # Keep only the first selection

# Attach observer to the heatmap selection
heatmap.observe(on_selection, names='selected')

## Step 6: Put it all together in a dashboard

Create a dashboard variable **called `dashboard`**.  On the left side of this dashboard place the `fig` heatmap figure and on the right place the bar plot figure, `fig_bars`.

In [10]:
#grade (write your code in this cell and DO NOT DELETE THIS LINE)
from ipywidgets import HBox

dashboard = HBox([fig, fig_bars])
dashboard

HBox(children=(Figure(axes=[Axis(label='A', scale=OrdinalScale(), side='bottom'), Axis(label='C', orientation=…